/*
 * This file is generated by jOOQ.
 */
package net.toadless.radio.jooq;


import net.toadless.radio.jooq.tables.Guilds;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.guilds</code>.
     */
    public static final Guilds GUILDS = Guilds.GUILDS;
}
