/*
 * This file is generated by jOOQ.
 */
package net.toadless.radio.jooq;


import net.toadless.radio.jooq.tables.DiscordTokens;
import net.toadless.radio.jooq.tables.Guilds;
import net.toadless.radio.jooq.tables.RefreshTokens;
import net.toadless.radio.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.discord_tokens</code>.
     */
    public static final DiscordTokens DISCORD_TOKENS = DiscordTokens.DISCORD_TOKENS;

    /**
     * The table <code>public.guilds</code>.
     */
    public static final Guilds GUILDS = Guilds.GUILDS;

    /**
     * The table <code>public.refresh_tokens</code>.
     */
    public static final RefreshTokens REFRESH_TOKENS = RefreshTokens.REFRESH_TOKENS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
