/*
 * This file is generated by jOOQ.
 */
package net.toadless.radio.jooq.tables.records;


import net.toadless.radio.jooq.tables.Guilds;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildsRecord extends UpdatableRecordImpl<GuildsRecord> implements Record3<Long, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guilds.guild_id</code>.
     */
    public GuildsRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.guilds.dj_role</code>.
     */
    public GuildsRecord setDjRole(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.dj_role</code>.
     */
    public Long getDjRole() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.guilds.prefix</code>.
     */
    public GuildsRecord setPrefix(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.prefix</code>.
     */
    public String getPrefix() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Guilds.GUILDS.GUILD_ID;
    }

    @Override
    public Field<Long> field2() {
        return Guilds.GUILDS.DJ_ROLE;
    }

    @Override
    public Field<String> field3() {
        return Guilds.GUILDS.PREFIX;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Long component2() {
        return getDjRole();
    }

    @Override
    public String component3() {
        return getPrefix();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Long value2() {
        return getDjRole();
    }

    @Override
    public String value3() {
        return getPrefix();
    }

    @Override
    public GuildsRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildsRecord value2(Long value) {
        setDjRole(value);
        return this;
    }

    @Override
    public GuildsRecord value3(String value) {
        setPrefix(value);
        return this;
    }

    @Override
    public GuildsRecord values(Long value1, Long value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildsRecord
     */
    public GuildsRecord() {
        super(Guilds.GUILDS);
    }

    /**
     * Create a detached, initialised GuildsRecord
     */
    public GuildsRecord(Long guildId, Long djRole, String prefix) {
        super(Guilds.GUILDS);

        setGuildId(guildId);
        setDjRole(djRole);
        setPrefix(prefix);
    }

    /**
     * Create a detached, initialised GuildsRecord
     */
    public GuildsRecord(net.toadless.radio.jooq.tables.pojos.Guilds value) {
        super(Guilds.GUILDS);

        if (value != null) {
            setGuildId(value.getGuildId());
            setDjRole(value.getDjRole());
            setPrefix(value.getPrefix());
        }
    }
}
