/*
 * This file is generated by jOOQ.
 */
package net.toadless.radio.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiscordTokens implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          userId;
    private final String        accessToken;
    private final String        refreshToken;
    private final LocalDateTime expiry;

    public DiscordTokens(DiscordTokens value) {
        this.userId = value.userId;
        this.accessToken = value.accessToken;
        this.refreshToken = value.refreshToken;
        this.expiry = value.expiry;
    }

    public DiscordTokens(
        Long          userId,
        String        accessToken,
        String        refreshToken,
        LocalDateTime expiry
    ) {
        this.userId = userId;
        this.accessToken = accessToken;
        this.refreshToken = refreshToken;
        this.expiry = expiry;
    }

    /**
     * Getter for <code>public.discord_tokens.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.discord_tokens.access_token</code>.
     */
    public String getAccessToken() {
        return this.accessToken;
    }

    /**
     * Getter for <code>public.discord_tokens.refresh_token</code>.
     */
    public String getRefreshToken() {
        return this.refreshToken;
    }

    /**
     * Getter for <code>public.discord_tokens.expiry</code>.
     */
    public LocalDateTime getExpiry() {
        return this.expiry;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DiscordTokens (");

        sb.append(userId);
        sb.append(", ").append(accessToken);
        sb.append(", ").append(refreshToken);
        sb.append(", ").append(expiry);

        sb.append(")");
        return sb.toString();
    }
}
