/*
 * This file is generated by jOOQ.
 */
package net.toadless.radio.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Guilds implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long   guildId;
    private final Long   djRole;
    private final String prefix;

    public Guilds(Guilds value) {
        this.guildId = value.guildId;
        this.djRole = value.djRole;
        this.prefix = value.prefix;
    }

    public Guilds(
        Long   guildId,
        Long   djRole,
        String prefix
    ) {
        this.guildId = guildId;
        this.djRole = djRole;
        this.prefix = prefix;
    }

    /**
     * Getter for <code>public.guilds.guild_id</code>.
     */
    public Long getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.guilds.dj_role</code>.
     */
    public Long getDjRole() {
        return this.djRole;
    }

    /**
     * Getter for <code>public.guilds.prefix</code>.
     */
    public String getPrefix() {
        return this.prefix;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Guilds (");

        sb.append(guildId);
        sb.append(", ").append(djRole);
        sb.append(", ").append(prefix);

        sb.append(")");
        return sb.toString();
    }
}
