/*
 * This file is generated by jOOQ.
 */
package net.toadless.radio.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RefreshTokens implements Serializable {

    private static final long serialVersionUID = 1L;

    private final UUID          tokenId;
    private final Long          userId;
    private final LocalDateTime expiry;

    public RefreshTokens(RefreshTokens value) {
        this.tokenId = value.tokenId;
        this.userId = value.userId;
        this.expiry = value.expiry;
    }

    public RefreshTokens(
        UUID          tokenId,
        Long          userId,
        LocalDateTime expiry
    ) {
        this.tokenId = tokenId;
        this.userId = userId;
        this.expiry = expiry;
    }

    /**
     * Getter for <code>public.refresh_tokens.token_id</code>.
     */
    public UUID getTokenId() {
        return this.tokenId;
    }

    /**
     * Getter for <code>public.refresh_tokens.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.refresh_tokens.expiry</code>.
     */
    public LocalDateTime getExpiry() {
        return this.expiry;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RefreshTokens (");

        sb.append(tokenId);
        sb.append(", ").append(userId);
        sb.append(", ").append(expiry);

        sb.append(")");
        return sb.toString();
    }
}
