on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ######################################################## generate gradle secrets
      - uses: actions/checkout@v3
      - name: create gradle.properties
        shell: bash
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          RADIO_DB_URL: ${{ secrets.RADIO_DB_URL }}
          RADIO_DB_USER: ${{ secrets.RADIO_DB_USER }}
          RADIO_DB_PASSWORD: ${{ secrets.RADIO_DB_PASSWORD }}
        run: |
          mkdir -p ~/.gradle/
          echo "::set-env name=GRADLE_USER_HOME::$HOME/.gradle"
          echo "RADIO_DB_URL=$RADIO_DB_URL" >> ~/.gradle/gradle.properties
          echo "RADIO_DB_USER=$RADIO_DB_USER" >> ~/.gradle/gradle.properties
          echo "RADIO_DB_PASSWORD=$RADIO_DB_PASSWORD" >> ~/.gradle/gradle.properties



        ######################################################## setup jdk
      - name: set up JDK 15
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '15'
          distribution: "adopt"



        ######################################################## setup gradle
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6



        ######################################################## build gradle
      - name: build project
        run: |
          ./gradlew clean build



        ######################################################## release on github
      - name: create release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: "2.0.0"
          allowUpdates: true
          artifacts: |
            LICENSE
            build/libs/radio-dashboard-backend-all.jar



        ######################################################## setup docker
      - name: setup buildx
        uses: docker/setup-buildx-action@v2.5.0



        ######################################################## login to dockerhub
      - name: login to dockerhub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}



        ######################################################## build and push the image
      - name: build and push
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            toadsy/radio-dashboard-backend:latest